- name: 下载jdk1.7.0_79包
  get_url:
      url: "{{jdk_down_url}}"
      dest: "{{soft_path}}"
      headers: "Cookie: oraclelicense=accept-securebackup-cookie"
      validate_certs: no

- name: 安装jdk1.7.0_79包
  unarchive:
      copy: no 
      src: "{{soft_path}}/{{jdk_name}}.tar.gz"
      dest: "{{pro_path}}"
      owner: root
      group: root
      mode: 0755

- name: 添加jdk1.7.0_79环境变量
  shell: /bin/bash {{soft_path}}/jdk_conf.sh

- name: source /etc/profile
  shell: source /etc/profile
